AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a secure S3 bucket for storing OpenVPN files.

Resources:
  OpenVPNFileBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AWS::AccountId}-${AWS::Region}-openvpn-files'
      # Enable encryption at rest using AWS-managed keys (SSE-S3)
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      # Public access block configuration
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

Outputs:
  OpenVPNFileBucketName:
    Description: 'Name of the S3 bucket for OpenVPN files'
    Value: !Ref OpenVPNFileBucket
    Export:
      Name: OpenVPNFileBucketName
